mod cfg;
mod check_elimination;
mod cleanup;
mod dce;
mod dse;
mod gvn;
mod inline;
mod licm;
mod load_forward;
mod memory;
mod rewrite;
mod sccp;

pub(crate) use cfg::run_cfg_canonicalize;
pub(crate) use check_elimination::run_check_elimination;
pub(crate) use cleanup::run_cleanup;
pub(crate) use dce::run_dead_code_elimination;
pub(crate) use dse::run_dead_store_elimination;
pub(crate) use gvn::run_gvn;
pub(crate) use inline::run_effect_aware_inline;
pub(crate) use licm::run_licm;
pub(crate) use load_forward::run_load_forwarding;
pub(crate) use memory::run_memory_ssa_refine;
pub(crate) use sccp::{ScalarAnalysisCache, run_sccp_range};
