schema = 1
version = "22.1.8"
tag = "llvmorg-22.1.8"
commit = "ca7933e47d3a3451d81e72ac174dcb5aa28b59d1"
archive = "llvm-project-22.1.8.src.tar.xz"
url = "https://github.com/llvm/llvm-project/releases/download/llvmorg-22.1.8/llvm-project-22.1.8.src.tar.xz"
sha256 = "922f1817a0df7b1489272d18134ee0087a8b068828f87ac63b9861b1a9965888"
host_only = true
static_only = true

[provenance]
license_files = ["LICENSE.TXT", "LLD-LICENSE.TXT", "third-party/BLAKE3-LICENSE", "third-party/COPYRIGHT.regex"]
license_sha256 = ["3340babe8ac7bc6ae294d93aa01c310a250d43d5b760e5c12954882d4e5c83c7", "f7891568956e34643eb6a0db1462db30820d40d7266e2a78063f2fe233ece5a0", "6a94bedb8b707ed97f6e310d0d015ab14e0683ffa0a612b02958581b9cc9fc0e", "0424e57d4303164dc59a8509c20dae0518b853692e5c2b0e98b11816fdbc97c7"]

[cmake]
build_type = "Release"
msvc_runtime_library = "MultiThreaded"
assertions = true
build_shared_libs = false
build_llvm_dylib = false
build_llvm_c_dylib = false
link_llvm_dylib = false
enable_rtti = false
enable_eh = false
enable_zlib = false
enable_zstd = false
enable_libxml2 = false
enable_terminfo = false
enable_libedit = false

[profiles.release]
projects = ["lld"]
include_clang = false
install_tools = ["llvm-config", "llvm-readobj"]
link_components = ["core", "native", "orcjit", "nativecodegen", "lto"]

[profiles.oracle]
projects = ["clang", "lld"]
runtimes = ["compiler-rt"]
include_clang = true
install_tools = ["clang", "llvm-config", "llvm-readobj", "llvm-profdata"]
compiler_rt_components = ["profile"]

[targets.darwin-arm64]
llvm_target = "AArch64"
lld_driver = "MachO"
orc_layer = "JITLink"
minimum_os = "11.0"

[targets.darwin-x64]
llvm_target = "X86"
lld_driver = "MachO"
orc_layer = "JITLink"
minimum_os = "11.0"

[targets.linux-arm64]
llvm_target = "AArch64"
lld_driver = "ELF"
orc_layer = "JITLink"

[targets.linux-x64]
llvm_target = "X86"
lld_driver = "ELF"
orc_layer = "JITLink"

[targets.win32-arm64]
llvm_target = "AArch64"
lld_driver = "COFF"
orc_layer = "RuntimeDyld"
extra_link_components = ["libdriver", "windowsmanifest"]

[targets.win32-x64]
llvm_target = "X86"
lld_driver = "COFF"
orc_layer = "JITLink"
extra_link_components = ["libdriver", "windowsmanifest"]
